// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vycwklwugmrndknqepsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5Y3drbHd1Z21ybmRrbnFlcHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTUzNDQsImV4cCI6MjA3Mjc3MTM0NH0.RIabNiPRscYXpu4_jnwBRF62NkxYZ-ckSRWdNsJpV14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});